services:
  node:
    build: .
    restart: always # restart the container if it stops for any reason
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    networks:
      - home-network
    volumes:
      # reloading project with changes
      - .:/nodejs-service # Mount entire project
      - /nodejs-service/node_modules # Prevents overwriting node_modules if reloading
      # storage for database data and PostgreSQL logs
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
    command: ['npm', 'run', 'start:dev']

  postgres:
    build: ./src/
    restart: on-failure # Restart only on failure, not when manually stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - home-network

networks:
  home-network:
    driver: bridge

volumes:
  db-data:
  db-logs:
